name: Pull Request Message
on:
  pull_request:
    paths: [features/*]
    types: [opened]
jobs:
  comment:
    permissions: write-all
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment on pull request 
        uses: thollander/actions-comment-pull-request@v3 
        with:
          issue-number: ${{ github.event.pull_request.number }}
          message: |
            I appreciate your comment! :wave: :fire:
          reactions: eyes, rocket